### ISSUE TITLE
Not opening : Delete dust, bubbles and other bad regions

### ISSUE THREAD

**Issue by mxardre** [wiggins-lab/SuperSegger#1]
Hi,
I am trying to use this amazing tool.
To do so I follow the instructions there : https://github.com/wiggins-lab/SuperSegger/wiki/Creating-your-own-constants-file
However when I want to train the software I do not manage to go from **Providing the algorithm with examples ** to Delete dust, bubbles and other bad regions.
The window to delete dust and bubble does not open. When a start the segmentation I got a warning : 

```
Warning: File '~/Desktop/training/phase/xy1/phase/xy1/seg/.trackOptiStripSmall-Step1.mat' not found. 
> In cleanSuperSegger (line 46)
  In BatchSuperSeggerOpti>intProcessXY (line 308)
  In parallel_function (line 476)
  In BatchSuperSeggerOpti (line 212)
  In trainingGui>cut_and_seg_Callback (line 129)
  In gui_mainfcn (line 95)
  In trainingGui (line 39)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)trainingGui('cut_and_seg_Callback',hObject,eventdata,guidata(hObject)) 

```
And then the window "Training new segmentation constant" is reset.

Any idea?
Im running on mac osx 10.10.5, matlab R2016b

**Comment by stellastyl** [comment]
The warning is totally fine - it should not stop the program. Did it stop at that point? I would be happy to look into it if you send me 5-10 of the pictures you were using. I did fix a couple of things recently, could you please download the newest version of SuperSegger and try it again? Just to make sure this wasn't from an older version!

Thank you!

**Comment by mxardre** [comment]
Hi,Thanks a lot!
I can show you with a google hangout if you would like. I don't know what time it is for you (23h for me). It is possible for me in 1h20.Maxime

-------- Message d'origine --------
De : Stella <notifications@github.com> 
Date : 23/01/2017  21:41  (GMT+01:00) 
À : wiggins-lab/SuperSegger <SuperSegger@noreply.github.com> 
Cc : mxardre <maxime.ardre+git@gmail.com>, Author <author@noreply.github.com> 
Objet : Re: [wiggins-lab/SuperSegger] Not opening : Delete dust, bubbles and
  other bad regions (#1) 

The warning is totally fine - it should not stop the program. Did it stop at that point? I would be happy to look into it if you send me 5-10 of the pictures you were using. I did fix a couple of things recently, could you please download the newest version of SuperSegger and try it again? Just to make sure this wasn't from an older version!
Thank you!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wiggins-lab/SuperSegger","title":"wiggins-lab/SuperSegger","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wiggins-lab/SuperSegger"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stellastyl in #1: The warning is totally fine - it should not stop the program. Did it stop at that point? I would be happy to look into it if you send me 5-10 of the pictures you were using. I did fix a couple of things recently, could you please download the newest version of SuperSegger and try it again? Just to make sure this wasn't from an older version!\r\n\r\nThank you!"}],"action":{"name":"View Issue","url":"https://github.com/wiggins-lab/SuperSegger/issues/1#issuecomment-274610372"}}}

**Comment by mxardre** [comment]
Solved thanks to stellastyl.
Reopening of the xy1/seg/ in the window "Training new segmentation constant" by clicking on the file in the toolbar.
