### ISSUE TITLE
modify manually the linking

### ISSUE THREAD

**Issue by imihalce** [wiggins-lab/SuperSegger#10]
Hi Stella,
I recently discovered Super Segger and really enjoy it,  for the constant learning part, and for the gating utilities and graphs etc . Really excellent. However, for some of my images the tracking  (linking) makes some mistakes and for some bad phase images (but acquired with great difficulty , I would not want to make the experiment again) it become even more difficult (the segmentation works perfectly, trough the neural network training). So I don't know if you plan to write a second training for the linking, or even an editing for the links, but in the mean time would it be possible to indicate how to correct manually in different files the linking (or if you have a small routine) to the get further with the analysis. 
I mean which files should be corrected if for example starting from a given time point cells 20 and 21 are inverted . 
Thanks for any indication

best
Irina

**Comment by stellastyl** [comment]
Hi Irina, 
I am glad you enjoy the software.
Unfortunately, we don't have a routine to manually correct links, we just throw the cells away in our analysis (using the gating utilities). 
I started working on a manual way to fix the linking, but it's not done yet.
- Stella

**Comment by imihalce** [comment]
Hi Stella,

OK. If you want us to try any alpha version of the manual linking routine, we will gladely do it !
best

Irina

**Comment by stellastyl** [comment]
Hi Irina,

I have added a beta version of manually linking routine. You can download the new version of SuperSegger and try it out through SuperSeggerViewerGui. I put some basic instructions in the wiki under 'Edit Links'.

Please let me know if you find any problems or if you have any suggestions.
Best,
Stella

**Comment by imihalce** [comment]
Waou that's excellent news! I will look into it and let you know.
thank you

best 
Irina
