### ISSUE TITLE
Clist doesnt exist

### ISSUE THREAD

**Issue by teranmickens** [wiggins-lab/SuperSegger#11]
Hello! I segmented my images, went to the ViewerGui to analyze, but i couldn't save the clist. Nor could most of the commands work because it said 'no clist loaded, these commands will not work'. I'm not sure why this said this when I just finished segmented them.

**Comment by stellastyl** [comment]
Hello!
Which folder are you loading? It should be the outermost folder that
contains the xy1, etc folders and the the raw_im folder. If you are loading
from the wrong directory it won't be able to find the clist.
What do you see when you load your images? Just images or also the cell
outlines?
And do you see a clist file in your xy directories?
Best,
Stella
