### ISSUE TITLE
File doesn't exist 

### ISSUE THREAD

**Issue by vrkrshna** [wiggins-lab/SuperSegger#13]
Hello guys,

After a few successful runs, supersegger throws an error saying "Error using imread>get_full_filename". "path/to/file/File doesn't exists". I don't know how to fix this. 

Venkata Rao Krishnamurthi

**Comment by stellastyl** [comment]
Hi! Could you post some more information? What were the messages before? Is this during alignment?

**Comment by vrkrshna** [comment]
Hi. Thanks for getting back to my question. The problem was with the naming convention. Even though Supersegger approved the naming style it threw that error. When I changed the file name to a different style, It worked fine.

**Comment by pawiggins** [comment]
vrkrshna:

The name parsing is a really difficult issue. You are typically better off writing your own script to re-write the names if you want SS to be a longer term solution for your research.

--PAW
