### ISSUE TITLE
Cell Length/width NAN

### ISSUE THREAD

**Issue by vrkrshna** [wiggins-lab/SuperSegger#14]
I have about 1000 frames per folder, after a few hundred frames/files, the cell length and short axis values are NAN. When I removed the first few frames and reran them, I had cell length and short axis values for few tens of frames and then again had NAN for the rest of the frames. I guess I am setting some constant wrong. What Am I missing? 

Thanks.

**Comment by pawiggins** [comment]
Can you provide a little more detail about what was nan and where? Was it entries in the clist matrices?
