### ISSUE TITLE
Add new segments

### ISSUE THREAD

**Issue by imihalce** [wiggins-lab/SuperSegger#16]
Hi
I use now a lot Super Segger. But some long run experiments, not always perfect optically, need some manual curing. Now that the manual link correction work, ( that helped a lot !!) would it be possible (in the long run) to add one or two more features:
-in the Edit segment  a manual tool where we would be able to add an new (inexistent) segment  
- in the same window would it be possible (once manually cured) to check a box telling the optimization algorithm to hold those segments and unchange their designation. 
And last but not least I would like to have the same check box in the link Editor (as if a later segment edition erase all the link connections)

thanks again
Irina

**Comment by pawiggins** [comment]
Hi Irina:

That is an interesting idea that we had considered but it hasn't been a huge priority... I'll chat with people in the group and see if anyone wants to add this feature.

Our general strategy is usually just to ignore cells with problems in our analyses.

--PAW

**Comment by imihalce** [comment]
Hi and thank you for your answer. Yes for other experiment is exactly what we are doing, just ignoring the badly segmented cells. And that works perfectly. However for these experiments they are long run with not so many cells, but that have to be followed all along so is crucial to not loose them. We tried to get around, suppressing some frames who  "depressingly" getting us bad segments, but I think that would be much more easy just add some manual segments.
My comment went along also with another question: it seems that when now that a successive segment editing suppress sometime the previously manually corrected segments. Would it be possible to have a flag for each frame were we would say to Segger do not change the segments here, do your optimisation before and after but not on this frame.

thanks a lot 
Irina

**Comment by pawiggins** [comment]
Hey Irina:

You can now create segments in "Edit Segments."

--PAW

**Comment by imihalce** [comment]
Hi 
and thank you for addressing so fast the issue . I updated now the Segger and it appears that the last version has some mishaps. I just have restarted a segmentation went for a coffee and when back, Segger produced something like open 300 figures. Could you keep the same configuration as before, to overwrite a new segmentation figure on top of the previous one ? Also in the SuperSeggerViewerGui the input for link editing is missing (from the wiki screen shot of the Viewer too). 

best 
Irina

**Comment by pawiggins** [comment]
Hmmm…

When do the figures open and what do they have in them?

**Comment by imihalce** [comment]
Hi,
These figures are generated  after the initial segmentation (end of step 2) and are some chunks of image (I bet is all around the problematic segment) with the segments superimposed on the phase image.
