### ISSUE TITLE
Info about generation

### ISSUE THREAD

**Issue by RoxaneMo** [wiggins-lab/SuperSegger#17]
Hello,

Where can I find information about number of generation? I want to know for each cell if it belongs to the first, second, third generation...
I saw information about the age of the old pole but what I would like to know is the generation of the cells regardless the time they took to divide. 

Thank you.
Roxane

**Comment by pawiggins** [comment]
Hey Roxane:

That information doesn't exist yet but would be easy to compute. Next time I edit the code, I will add that feature in the clist.

But for now...  load up the clist. For cells that don't have mothers, set generation 0. For cells with mothers in generation 0, set generation 1, etc.

I would use the MATLAB builtin function ismember.

--PAW

**Comment by RoxaneMo** [comment]
Hello,

Thanks for your answer that helped me.
Instead of starting with cells that don't have mothers, I started with cells that have "Cell birth time"=1 because I don't consider cells that I cannot follow the genealogy from the first frame.

Roxane

**Comment by pawiggins** [comment]
Yeah....I agree that for many applications, this is what you want.

**Comment by pawiggins** [comment]
Roxane:

This is now in the clist.

--PAW
