### ISSUE TITLE
Genealogy-Tree

### ISSUE THREAD

**Issue by RoxaneMo** [wiggins-lab/SuperSegger#18]
Hello,

I need to know all the cells that belong to the same genealogy tree.
Is there an easy way to obtain this information from the "clist"?
I would give a different number to all the cells at frame 1 and then give the same corresponding number to the daughters and so on. Do you have suggestions or an easier way to do it?

Thank you.
Roxane

**Comment by pawiggins** [comment]
Hey Roxane:

All the code already essentially exists in the "Lineage" function in the viewer. (Top right.) Next time I update the code, I'll add this to the clist.

--PAW

**Comment by pawiggins** [comment]
Hey Roxane:

I pushed these changes just now. Generation, Generation0 and Progenitor are added to the clist. 

Generation0 = generation relative to progenitor (but only frame 1 progenitors are allow )
Generation   = generation relative to progenitor
progenitor    = progenitor cell ID.

--PAW
