### ISSUE TITLE
Training for the segments - clicking on segments not working

### ISSUE THREAD

**Issue by showmepuppies** [wiggins-lab/SuperSegger#20]
Hi,

I am currently training my own constants. When running the training Gui, I can see the masks and I am able to remove debris etc. But when I toggle "display segments", and click on a segment, it does not change color/assignment, and I get the following error message:

```
>> trainingGui

Reference to non-existent field 'whichButton'.

Error in updateTrainingImage (line 42)
    if FLAGS.whichButton ==
    FLAGS.EdgeToggleRadioButtonFlag;

Error in trainingGui>imageButtonDownFcn (line 731)
    [settings_train.currentData, list] =
    updateTrainingImage(settings_train.currentData,
    FLAGS, eventdata.IntersectionPoint(1:2));

 Error while evaluating Image ButtonDownFcn.
```
Each click (whether on a segment or not) triggers the same messages.

Matlab version 2018a, Windows 10

Best,
Elisa

**Comment by pawiggins** [comment]
Hey Elisa:

What version of ss are you using? Maybe check out an older version. My guess is that when we updated the segment editing capabilities, we introduced a bug in training.

If you are using the most recent version, maybe rewind to a pre July version. I’ll look at it when I get a chance but I am at a conference at the moment.

—PAW

**Comment by pawiggins** [comment]
Hi Elisa:

Ok… I messed this up when I added more segment editing capabilities a couple weeks ago. It should be fixed now. Hit an update and you should be fine.

—PAW

**Comment by showmepuppies** [comment]
Thanks a lot for the quick fix! Works like a charm now.
