### ISSUE TITLE
Plotting Fluorescence Histograms 

### ISSUE THREAD

**Issue by showmepuppies** [wiggins-lab/SuperSegger#27]
In superSeggerViewerGui, when I try to plot "Fluor1 sum" (or Fluor1 mean, Fluor2 sum, Fluor2 mean) I don't get any fluorescence values on the plot (see image below). Segmentation works fine, and the fluorescence is overlayed on the segments correctly.

Bad plot, showing no fluorescence:
![Fluor1sum](https://user-images.githubusercontent.com/15034855/57702624-60836680-7656-11e9-8110-4dc62e86270f.JPG)

Screenshot showing fluorescence overlayed on segments:
![view1](https://user-images.githubusercontent.com/15034855/57703230-8eb57600-7657-11e9-92c3-d1069a0a51ca.JPG)

What could be causing this issue? All channels are .tif, 8-bit.

**Comment by stellastyl** [comment]
Did you have 'Fluorescence statistics' set as true when your run SuperSegger? That would cause Supersegger to not calculate any fluorescence measures. 
You can check one of the 'Cell files' (https://github.com/wiggins-lab/SuperSegger/wiki/The-cell-data-files) it should have fl1 filled with data if the statistics are there.
Let me know if this helps. You can also sent us your data and we can take a look.

**Comment by showmepuppies** [comment]
Yes I did not tick Fluo statistics. Thanks!
