### ISSUE TITLE
Error on Macbook (2010, v10.12.4 with Matlab 2014b)

### ISSUE THREAD

**Issue by daimonie** [wiggins-lab/SuperSegger#4]
Hey guys,

While working with SuperSegger we ran into an error. The error is that subscript indices should be real or positive integers or logicals on line 33 of scoreNeuralNet.m. It looks like the array 'x' is both positive and negative floating point numbers.

I hope you can fix it with this information.

Cheers,
Josko de Boer,
Nynke Dekker Lab

**Comment by stellastyl** [comment]
Hi Josko,

I can look into it, but I need the images where this issue showed up and the 'Constants' you used. Also could you make sure you are using the latest version of SuperSegger? If you downloaded SuperSegger a whole ago, download the code again and run it once more.

Thanks,
Stella

**Comment by daimonie** [comment]
Hey Stella,

I will try to get you some more information. SuperSegger was pulled from git yesterday. The constants can be found here: https://github.com/daimonie/Agarolysis/blob/master/functions/seggerFunctions/applySuperSegger.m

I will try to get a minimal amount of images to get the error and send them to you by e-mail. Note that the images worked on two separate windows installations, one in matlab 2015(b) and the other in 2016(?).

Cheers,
Josko

**Comment by daimonie** [comment]
Hey Stella,

The 'Constants' might also refer to "60XBay", I just realised. With this, you have a full overview of the parameters given to SuperSegger. I'll try to replicate the error on the researcher's macbook.

Cheers,
Josko

**Comment by stellastyl** [comment]
This happens only in matlab 2014? I don't currently have a computer with matlab 2014. Is it just this set of images or does it not work for any images in matlab 2014? The line you pointed out uses the neural network toolbox from matlab. If matlab 2014 did not have the toolbox or matlab made some changes in the toolbox between 2014 and 2015 then it may not work at all in matlab 2014.
