### ISSUE TITLE
Invalid MEX-file '/Users/...../SuperSegger-master/fastRotate/fast_rotate_loose_double.mexmaci64' is not a valid shared library..

### ISSUE THREAD

**Issue by nhuwiler** [wiggins-lab/SuperSegger#5]
Hi,
I was running the trySuperSegger.m file on my computer (MacBook Pro 13-inch, 2016,2.9 GHz Intel Core i5,8 GB 2133 MHz LPDDR3) and I am getting this error message in Matlab after I selected the crop region (in the trySuperSegger.m file the execution has problems with the "tryDifferentConstants([dirname,'/raw_im/']);" command on line 30). The MEX-file is where it should be and the path was added following the instructions. Is it possible that there is a problem with the file itself?

**Comment by stellastyl** [comment]
It may be a problem with your matlab version and the version the file was compiled. What matlab version are you using?

**Comment by stellastyl** [comment]
I have recompiled the 'mex' file with the newest matlab. Can you download SuperSegger again and give it a try now?

**Comment by nhuwiler** [comment]
Cool, thanks for recompiling! It works perfectly now!
PS: I am using Matlab R2017a
