### ISSUE TITLE
Accurate Foci Recognition

### ISSUE THREAD

**Issue by jason-dennis11** [wiggins-lab/SuperSegger#6]
Hi, 
I am using the SuperSegger program on an E. coli population with fluorescence. I was wondering if there is any way to a export a visual (i.e. gaussian fitting curve) to demonstrate/validate the recognition of foci in the fluorescence channels. 

Thank you

**Comment by stellastyl** [comment]
Hi Jason,
The information about the gaussian curve is in each cell file under locus1(x)
More info here (https://github.com/wiggins-lab/SuperSegger/wiki/The-cell-data-files)
intensity: raw maximum intensity of the focus
shortaxis: focus position along the cell’s short axis in local coordinates (0 is the cell center)
longaxis: focus position along the cell’s long axis in local coordinates (0 is the cell center)
fitSigma: standard deviation (spread) of gaussian fit to the focus.

You can plot the gaussian using the information above.

There is also some debug tools we have in the foci fitting (https://github.com/wiggins-lab/SuperSegger/blob/master/fluorescence/intFindFociCurve.m) that do some of this plots, but were used mainly for debugging. If you set the Debug_flag to true, and run foci finding again it will show some plots (the raw image, the mask of the fit of the gaussian, and the raw image cropped to the mask of the gaussian). You could to do something similar like the "makeGassianTestImage" function in there, using the info in the cell files.

Best,
Stella
