### ISSUE TITLE
Training with Examples

### ISSUE THREAD

**Issue by teranmickens** [wiggins-lab/SuperSegger#7]
Hello! I am using a Dell desktop and keep running into an issue where I need to provide the algorithm with examples. The movie has been cropped and there's 90 images, but every 3 are being segmented. The action panel didn't pop up immediately after 'start segmentation' so I went into the command center and inputted trainingGui to run it and then chose the 60XEc constant. I made sure that the MATLAB folder on the left panel matched up and is at xy1/seg. The issue that I keep having is that when the 'Training new segmentation constants' screen pops up, the Actions section on the right hand side doesn't appear. So I cannot progress and click 'delete square.' Can you please try and explain to me steps I might take to make this Actions section appear, and help me see what I am doing wrong, if anything?

Thank you!
Teran

**Comment by stellastyl** [comment]
Hi Teran,

Sorry to hear that the Actions section does not appear. We had it tested in different platforms and computers but the matlab graphical interfaces can vary a lot from screen to screen.

Maybe it shows up but it is outside the screen?
Here are some suggestions:
1) Could you try it on a different computer?
2) Another person had a similar problem and moved things around - that changed messed up the graphical interfaces on my computer, but it may work for yours. Maybe try downloading the graphical interfaces from here and replacing the one in the supersegger folder: https://github.com/wiggins-lab/SuperSegger/issues/3
3) You can also move open the TrainingGui.fig and move the 'actions' panels to the left, and make them a bit smaller in case that helps.

**Comment by teranmickens** [comment]
Great!! Thank you, the second suggestion helped! Thank you for clarifying, it now works!
